ignored = ["github.com/Sirupsen/logrus"]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gravitational/kingpin"
  branch = "master"

[[constraint]]
  name = "github.com/gravitational/teleport"
  version = "2.3.5"

[[constraint]]
  name = "github.com/gravitational/trace"
  version = "1.1.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[override]]
  name = "github.com/russellhaering/gosaml2"
  revision = "8908227c114abe0b63b1f0606abae72d11bf632a"

[[override]]
  name = "github.com/sirupsen/logrus"
  source = "github.com/gravitational/logrus"
  revision = "e340a662ee7a1b9e3f6675182abed99b892189d6"
