apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-certs
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  azureFile:
    secretName: azure-secret
    shareName: certs
    readOnly: false
  claimRef:
    namespace: default
    name: az-certs
