apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: keygen
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: keygen
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}          
    spec:
      containers:
      - name: keygen
        image: quay.io/gravitational/keygen:{{ .Chart.Version }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1m        
        env:
        - name: KEYGEN_CERT
          value: "/var/lib/certs/crt"
        - name: KEYGEN_KEY
          value: "/var/lib/certs/key"
        - name: KEYGEN_HOSTPORT
          value: "0.0.0.0:8080"
        ports:
        - containerPort: 8080
          name: keygen
        volumeMounts:
        - mountPath: /var/lib/certs
          name: tls-web
          readOnly: true
      volumes:
      - name: tls-web
        secret:
          secretName: tls-web
